export enum SpecialKeys {
  Control = 'Control',
  Shift = 'Shift',
  Alt = 'Alt',
  Tab = 'Tab',
  ArrowLeft = 'ArrowLeft',
  ArrowUp = 'ArrowUp',
  ArrowRight = 'ArrowRight',
  ArrowDown = 'ArrowDown',
  Escape = 'Escape',
  Enter = 'Enter',
  // Backspace = 'Backspace',
  // Delete = 'Delete',
  CapsLock = 'CapsLock',
  End = 'End',
  Insert = 'Insert',
  Home = 'Home',
  PageUp = 'PageUp',
  PageDown = 'PageDown',
  NumLock = 'NumLock',
  Meta = 'Meta',
  AltGraph = 'AltGraph',
  ContextMenu = 'ContextMenu'
}
