// Generated by https://quicktype.io

import { User } from "src/app/auth/interfaces";

export interface UsersResponse {
  results: User[];
  meta:    Meta;
}

export interface Meta {
  totalItems:   number;
  itemCount:    number;
  itemsPerPage: number;
  totalPages:   number;
  currentPage:  number;
}
